#g++ -v -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib iri_index_test.cpp -o iri_index_test  -lsdsl -ldivsufsort -ldivsufsort64
#g++ -v -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib test.cpp -o test  -lsdsl -ldivsufsort -ldivsufsort64
g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib block_test.cpp ../src/db/block.cpp  -o block_test  
