#g++ -v -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib iri_index_test.cpp -o iri_index_test  -lsdsl -ldivsufsort -ldivsufsort64
#g++ -v -std=c++11 -O3 -DNDEBUG -I ~/include -L ~/lib test.cpp -o test  -lsdsl -ldivsufsort -ldivsufsort64
#g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib block_test.cpp ../src/db/block.cpp  -o block_test  
#g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib block_index_test.cpp ../src/db/block_index.cpp ../src/db/block.cpp  -o block_index_test  
#g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib root_table_test.cpp ../src/db/root_table.cpp  -o root_table_test  
#g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib block_data_seeker_test.cpp ../src/db/block.cpp ../src/core/triple.cpp  ../src/db/block_data_seeker.cpp -o block_data_seeker_test  
#g++ -v -std=c++11 -g -DNDEBUG -I ~/include -L ~/lib file_util_test.cpp ../src/utils/file_util.cpp  -o file_util_test  
#g++ -v -std=c++11 -DNDEBUG -I ~/include -L ~/lib iri_index_test.cpp -o iri_index_test  -lsdsl -ldivsufsort -ldivsufsort64
#g++ -v -std=c++11 -march=native -O3 roaring_test.cpp -o roaring_test 

#g++ -v -std=c++11 -g -DDEBUG -march=native -O3 fish_db_test.cpp -o fish_db_test ../src/db/block.cpp ../src/db/block_index.cpp ../src/db/root_table.cpp ../src/db/block_data_seeker.cpp ../src/core/triple.cpp ../src/core/fish_db_impl.cpp ../src/core/iri_type.cpp ../src/utils/file_util.cpp ../src/utils/roaring.c

#g++ -v -std=c++11 -g  -O1 sparql_test.cpp  -o sparql_test ../src/sparql/sparqllexer.cpp  ../src/sparql/sparqlparser.cpp ../src/sparql/sparqlplaner.cpp ../src/sparql/utils.cpp ../src/sparql/valuefilter_impl.cpp  

g++ -v -std=c++11 -g  -fsanitize=address -fno-omit-frame-pointer  -march=native -DDEBUG -O query_test.cpp  -o query_test ../src/query/triple_query.cpp ../src/query/query_executor.cpp ../src/sparql/sparqllexer.cpp  ../src/sparql/sparqlparser.cpp  ../src/sparql/utils.cpp ../src/sparql/valuefilter_impl.cpp  ../src/db/block.cpp ../src/db/block_index.cpp ../src/db/root_table.cpp ../src/db/block_data_seeker.cpp ../src/core/triple.cpp ../src/core/fish_db_impl.cpp ../src/core/iri_type.cpp ../src/utils/file_util.cpp ../src/utils/roaring.c

### debug
#g++ -v -std=c++11 -g -fsanitize=address -fno-omit-frame-pointer -DNDEBUG -march=native -O fish_db_test.cpp -o fish_db_test ../src/db/block.cpp ../src/db/block_index.cpp ../src/db/root_table.cpp ../src/db/block_data_seeker.cpp ../src/core/triple.cpp ../src/core/fish_db_impl.cpp ../src/core/iri_type.cpp ../src/utils/file_util.cpp ../src/utils/roaring.c




#boost
#g++ -v -std=c++11 -g -o boost_test boost_test.cpp 
